config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :messages, only: [:index, :create, :new, :edit, :update] do
    collection do
      get 'article', to: 'messages#article'
      get 'edit', to: 'messages#edit'
    end
  end
  
  resources :mypages, only: [:new, :show]

  root "messages#index"
end

app/models/answer.rb
class Answer < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  
  require 'mechanize'

  def psychology_urls
    agent = Mechanize.new
    page = agent.get('https://www.jstage.jst.go.jp/browse/jjpsy/-char/ja')
    @elements = page.search('li .clickable_div')

    @elements.each do |ele|
      article = Article.new
      article.url = ele.inner_text
      article.save
    end
  end
end

app/models/category.rb
class Category < ActiveHash::Base
  self.data = [{id: 1, name: '職場'}, {id: 2, name: '学校'},{id:3, name: '教育関係（保護者目線）'},{id: 4, name: '恋愛'}, {id: 5, name: '家庭'},{id:6, name: '隣人'}]

end

app/models/message.rb
class Message < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :question
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :yesno
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :category

  belongs_to :user

  validates :memo, null: false
  validates :category_id, presence: true
end

app/models/question.rb
class Question < ActiveHash::Base
  self.data = [{id: 1, name: 'あなたは今落ち込んでいますか？'}, {id: 2, name: 'あなたは今やる気がありますか？'},{id:3, name: 'あなたは今仕事に行きたいですか？'}]
end

app/models/scraping.rb
class Scraping < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :messages

  validates :name, presence: true
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :first_name_kana, presence: true
  validates :last_name_kana, presence: true
  validates :birthday, presence: true
  validates :password, presence: true, length: { minimum: 8 }
  validates :encrypted_password, presence: true, length: { minimum: 8 }
end

app/models/yesno.rb
class Yesno < ActiveHash::Base
  self.data = [{id: 1, name: 'YES', index: 1}, {id: 2, name: 'NO', index:1}, {id: 10, name: 'YES',index:2}, {id:20, name: 'NO', index:2}, {id:100, name: 'YES', index:3}, {id:200, name:'NO',index: 3}]
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :first_name, :last_name, :first_name_kana, :last_name_kana, :birthday] )
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
  @messages = Message.all
  end

  def new
    @message = Message.new
    @first_question = Yesno.find(1, 2)
    @category = Category.find(1)
  end

  def create
    @message = Message.new(answer_params)
    @category = Category.find(1)
    if @message.save
      redirect_to edit_messages_path
    else
      redirect_to new_message_path
    end

  def edit
    @message = Message.last
  end

  def update
    @message = Message.last
    @message.update(answer_params)
      if @message.memo.present?
          redirect_to article_messages_path
      else
         redirect_to edit_messages_path
      end
  end

  def article
    @message = Message.last
    @category1 = Message.where(category_id: 1)
    @category2 = Message.where(category_id: 2)
    @category3 = Message.where(category_id: 3)
    @category4 = Message.where(category_id: 4)
    @category5 = Message.where(category_id: 5)
    @category6 = Message.where(category_id: 6)
  end

end

  private

  def answer_params
    params.require(:message).permit(:memo, :category_id).merge(user_id: current_user.id)
  end

  # -if Message.last.firsr_answer.present?
  #     @message = Message.last
  # - elsif Message.last.second_answer.present?
  #     @message = Message.last
  # - else
  #     @message = Message.new
    

end

app/controllers/mypages_controller.rb
class MypagesController < ApplicationController
  def new
    
  end
  
  def show
    @users = User.find(params[:id])
  end

  def destroy
  end

end

app/controllers/scrapings_controller.rb
class ScrapingsController < ApplicationController
  require 'mechanize'

  def index
    agent = Mechanize.new
    page = agent.get('https://www.apple.com/jp/?afid=p238%7CsKSMckWTz-dc_mtid_18707vxu38484_pcrid_479606761351_pgrid_13140806301_&cid=aos-jp-kwgo-brand--slid---product--')
    # @elements = page
    @elements = page.search('.ac-gf-directory-column-section')
    # # @elements.get_attribute(:href)
    # # # @elements = page.search('')

    # @elements.each do |ele|
    #   @hoge = ele[:href]
     

  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/mypages_helper.rb
module MypagesHelper
end

app/helpers/scraping_helper.rb
module ScrapingHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title stress eraser
    %script{src: "https://js.pay.jp/", type: "text/javascript"}
    %script{src: "https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"}
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/layouts/messages/_main_chat.html.haml
.main-chat
  .main-chat__header
    .main-chat__header__group-info
      .main-chat__header__group-info__member-list
        Member：
        .main-chat__header__group-info__member-list__member
          - @group.users.each do |user|
            =user.name

    =link_to 'Edit',edit_group_path(@group), class: "main-chat__header__group-info__edit"

  .main-chat__list
    = render @messages
        
  .main-chat__message-form
    = form_with model: [@group, @message], html: {class: "new_message"}, local: true do |f|
      .input-box
        = f.text_field :content, class: 'input-box__text', placeholder: 'type a message'
        = f.label :image, class: 'input-box__image' do
          = icon('far', 'image', class: 'Form__icon')
          = f.file_field :image, class: 'input-box__image__file'
      = f.submit 'Send', class: 'submit-btn'

app/views/messages/_main_chat-btn.haml
- if user_signed_in?
  .answerBtn
    .answerBtn__text
    = link_to new_message_path(current_user.id), class: 'answerBtn__text' do
      answer

app/views/messages/_main_chat.html.haml
.toppage
  .header
    - if user_signed_in?
      .mypage
        = link_to mypage_path(current_user.id), class: 'mypage--btn' do
          マイページ
    - else
      .login
        = link_to user_session_path, class: 'login--btn' do
          ログイン
      .registration
        = link_to new_user_registration_path, class: 'registration--btn' do
          新規登録
  .main
    - if user_signed_in?
      .message
        では右下の「answer」ボタンを押して、
        %br あなたの悩みを消していきましょう
    - else
      %h3.welcome
        %i 〜 Welcome 〜
      .message
        あなたの悩みを
        %b "すとれすけしごむ"
        を使って
        %br 消していくアプリです
        %br では新規登録から始めていきましょう

app/views/messages/_message.html.haml
.MessageBox{data: {message: {id: message.id}}}
  .MessageInfo
    .MessageInfo__userName
      = message.user.name
    .MessageInfo__date
      = message.created_at.strftime("%Y年%m月%d日 %H時%M分")
  .Message
    - if message.content.present?
      %p.Message__content
        = message.content
    = image_tag message.image.url, class: 'Message__image' if message.image.present?

app/views/messages/article.html.haml
.article
  .article-proposal
    みんなからのすとれすけしごむです
    %br このけしごむであなたの悩みを消していきましょう
    .article-proposal__opinion
      -if @message.category_id == 1
        - @category1.shuffle.first(5).each do |m|
          %li
            = m.memo

      -if @message.category_id == 2
        - @category2.shuffle.first(5).each do |m|
          %li
            = m.memo

      -if @message.category_id == 3
        - @category3.shuffle.first(5).each do |m|
          %li
            = m.memo

      -if @message.category_id == 4
        - @category4.shuffle.first(5).each do |m|
          %li
            = m.memo

      -if @message.category_id == 5
        - @category5.shuffle.first(5).each do |m|
          %li
            = m.memo

      -if @message.category_id == 6
        - @category6.shuffle.first(5).each do |m|
          %li
            = m.memo







  .home-buttton
    = link_to root_path, class: 'home-buttton--btn' do
      toppage

app/views/messages/edit.html.haml
.answer
  .question
    Q.あなたと同じ悩みを抱えている人がいるとすると、
    %br あなたはどんな
    %b "すとれすけしごむ"
    を渡しますか？
  .selected-trouble
    -if @message.category_id == 1
      「 職場 」
    -if @message.category_id == 2
      「 学校 」
    -if @message.category_id == 3
      「 教育関係（保護者目線） 」
    -if @message.category_id == 4
      「 恋愛 」
    -if @message.category_id == 5
      「 家庭 」
    -if @message.category_id == 6
      「 隣人 」
  = form_with model: @message, local: true do |f|
    = f.text_area :memo, class: 'answer-form', placeholder: 'type a comment'
    .answer-btn
      = f.submit "answer", class: "answer-box"

app/views/messages/index.html.haml
.wrapper
  = render "main_chat"
  = render "main_chat-btn"

app/views/messages/new.html.haml
.answer
  = form_with model: @message, local: true do |f|
    .adler-text
      〜全ての悩みは対人関係である〜
      .adler-name
        アルフレッド・アドラー
    .discription
      あなたの悩みも行き着く先は対人関係のはずです
      %br それでは下の選択肢からあなたの悩みに近いものを選んでください
      
    .first-box_answer
      = f.collection_select :category_id,Category.all, :id, :name,{include_blank: "選択してください"},  {class: "details_select"}

    .answer-btn
      = f.submit "answer", class: "answer-box"

app/views/mypages/show.html.haml
.Mypage
  .profile-header
    プロフィール
  .profile-name
    .profile-name__icon
      = icon('far', 'user-circle fa-2x', class: 'user-icon')
      .profile-name__form
        = @users.name
  .mypage__logout
    =link_to destroy_user_session_path, method: :delete, class:"Mypage__logout--btn" do
      log out

app/views/scrapings/index.html.haml
-# .scraping
-#  = @hoge

-# - @elements.each do|element|
-#   %ul
-#     %li
-#       = link_to(element.inner_text,element[:href])
    
- @artcle